name: Chrono
description: A new Flutter project.

publish_to: "none"
version: 1.0.9+10

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  signature: ^5.0.0
  flutter_multi_select_items: ^0.4.2
  eva_icons_flutter: ^3.1.0
  rxdart: ^0.27.7
  http: ^1.1.0
  chat_gpt_sdk: ^2.2.4
  markdown_widget: ^2.2.0
  dart_openai: ^4.0.0
  flutter_svg: ^2.0.7
  grouped_list: ^5.1.2
  shared_preferences: ^2.2.2
  flexible_scrollbar: ^0.1.3
  url_launcher: ^6.2.2
  file_picker: ^8.0.3
  flutter_email_sender: ^6.0.3
  undo: ^1.5.0
  go_router: ^14.6.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  uuid: ^4.5.1
  get_it: ^8.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_time_picker_spinner: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600


flutter_intl:
  enabled: true
  main_locale: ru